analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Recommended Flutter/Dart lints; enable or tweak as your team prefers
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    unnecessary_null_in_if_null_operators: true
    prefer_is_empty: true
